# -*- coding: utf-8 -*-
"""
/***************************************************************************
 latlonbuffer
                                 A QGIS plugin
 This plugin makes a buffer in meters around lat lon point features
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-10-31
        copyright            : (C) 2022 by Morten Sickel
        email                : morten@sickel.net
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Morten Sickel'
__date__ = '2022-10-31'
__copyright__ = '(C) 2022 by Morten Sickel'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load latlonbuffer class from file latlonbuffer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .latlonbuffer import latlonbufferPlugin
    return latlonbufferPlugin()
